on:
  release:
    types: created

jobs:
  build:
    runs-on: [windows-2025-vs2026]
    strategy:
      matrix:
        python-version: ["3.13"]
    steps:
      - uses: actions/checkout@v5
      - name: Install the latest version of uv and set the python version
        uses: astral-sh/setup-uv@bec219d24cd3e171d82865faccec33120bb574f4 # v10.1.0
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install requirements
        run: uv sync --no-group dev
      - name: Build with python ${{ matrix.python-version }}
        run: uv run nuitka --standalone --enable-plugin=pyqt6 --windows-console-mode=disable --output-dir=dist --jobs=4 --lto=yes --nofollow-import-to=pytest,ruff --msvc=latest --noinclude-qt-translations --windows-icon-from-ico=assets/icon.ico --output-filename=apsat --onefile src/main.py
